"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { DndContext, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { GripVertical, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { adminRequest } from "@/lib/admin-client";
import { toast, toastError } from "@/components/admin/toast";
import type { DonprodProject } from "@/types/donprod";

export function ProjectsManager() {
  const [projects, setProjects] = useState<DonprodProject[] | null>(null);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("ALL");
  const [removing, setRemoving] = useState<DonprodProject | null>(null);
  const load = () => void adminRequest<DonprodProject[]>("/api/admin/projects").then(setProjects).catch((reason: unknown) => toastError(reason instanceof Error ? reason.message : "Something went wrong."));
  useEffect(load, []);
  const shown = useMemo(() => (projects ?? []).filter((project) => (filter === "ALL" || project.visibility === filter) && `${project.title} ${project.artist ?? ""}`.toLowerCase().includes(query.toLowerCase())), [projects, query, filter]);
  const toggle = async (project: DonprodProject) => { try { const updated = await adminRequest<DonprodProject>(`/api/admin/projects/${project.id}`, { method: "PATCH", body: JSON.stringify({ visibility: project.visibility === "VISIBLE" ? "HIDDEN" : "VISIBLE" }) }); setProjects((current) => current?.map((item) => item.id === project.id ? { ...item, ...updated } : item) ?? null); } catch (reason) { toastError(reason instanceof Error ? reason.message : "Unable to change visibility."); } };
  const remove = async () => { if (!removing?.id) return; try { await adminRequest(`/api/admin/projects/${removing.id}`, { method: "DELETE" }); setProjects((current) => current?.filter((project) => project.id !== removing.id) ?? null); setRemoving(null); toast("Project deleted."); } catch (reason) { toastError(reason instanceof Error ? reason.message : "Unable to delete project."); } };
  const reorder = async (event: DragEndEvent) => { if (!event.over || event.active.id === event.over.id || !projects) return; const oldIndex = projects.findIndex((project) => project.id === event.active.id); const newIndex = projects.findIndex((project) => project.id === event.over?.id); const next = arrayMove(projects, oldIndex, newIndex); setProjects(next); try { await adminRequest("/api/admin/projects/reorder", { method: "PATCH", body: JSON.stringify({ projectIds: next.map((project) => project.id) }) }); } catch (reason) { toastError(reason instanceof Error ? reason.message : "Unable to save project order."); load(); } };
  return <div>
    <div className="mb-6 flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-1 flex-col gap-3 sm:flex-row"><label className="flex max-w-lg flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 text-slate-400 focus-within:border-[#465fff] focus-within:ring-2 focus-within:ring-indigo-100"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects" className="w-full bg-transparent py-2.5 text-sm text-slate-800 outline-none placeholder:text-slate-400" /></label><select aria-label="Visibility filter" value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-[#465fff] focus:ring-2 focus:ring-indigo-100"><option value="ALL">All visibility</option><option value="VISIBLE">Visible</option><option value="HIDDEN">Hidden</option></select></div><Link href="/admin/projects/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#465fff] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#3a4fe6]"><Plus size={16} />New project</Link></div>
    {!projects ? <div className="grid min-h-[45vh] place-items-center rounded-2xl border border-dashed border-slate-200 bg-white text-sm text-slate-500">Loading projects</div> : projects.length === 0 ? <Empty /> : shown.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-10 text-center text-sm text-slate-500">No matching projects</div> : <ProjectList projects={shown} onToggle={toggle} onRemove={setRemoving} onReorder={reorder} />}
    {removing && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><p className="text-2xl font-semibold tracking-tight text-slate-900">Delete this project?</p><p className="mt-3 text-sm text-slate-600"><strong>{removing.title}</strong> will be permanently removed from the database.</p><div className="mt-7 flex justify-end gap-3"><button onClick={() => setRemoving(null)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancel</button><button onClick={remove} className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-red-700">Delete</button></div></div></div>}
  </div>;
}

function ProjectList({ projects, onToggle, onRemove, onReorder }: { projects: DonprodProject[]; onToggle: (project: DonprodProject) => void; onRemove: (project: DonprodProject) => void; onReorder: (event: DragEndEvent) => void }) { const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 7 } })); return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="min-w-[850px]"><div className="grid grid-cols-[35px_60px_1.5fr_1fr_1fr_100px_70px_115px] gap-3 border-b border-slate-100 bg-slate-50 px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-500"><span /><span>Thumb</span><span>Project</span><span>Tags</span><span>Video</span><span>Status</span><span>Views</span><span>Actions</span></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onReorder}><SortableContext items={projects.map((project) => project.id ?? project.slug)} strategy={verticalListSortingStrategy}>{projects.map((project) => <ProjectRow key={project.id} project={project} onToggle={onToggle} onRemove={onRemove} />)}</SortableContext></DndContext></div></div>; }

function ProjectRow({ project, onToggle, onRemove }: { project: DonprodProject; onToggle: (project: DonprodProject) => void; onRemove: (project: DonprodProject) => void }) { const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: project.id ?? project.slug }); return <div ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className="grid grid-cols-[35px_60px_1.5fr_1fr_1fr_100px_70px_115px] items-center gap-3 border-b border-slate-100 px-4 py-3 last:border-0 hover:bg-slate-50"><button {...attributes} {...listeners} className="cursor-grab text-slate-400 hover:text-slate-700" aria-label={`Reorder ${project.title}`}><GripVertical size={17} /></button><div className="h-10 rounded-lg bg-slate-100" style={{ background: project.thumbDesktop ? `center / cover url(${project.thumbDesktop})` : undefined }} /><div><p className="text-sm font-medium text-slate-900">{project.title}</p><p className="text-xs text-slate-500">{project.artist || "No artist"}</p></div><p className="truncate text-xs text-slate-500">{project.tags.join(", ") || "—"}</p><p className="text-xs text-slate-500">{project.videoType || "—"}</p><button onClick={() => onToggle(project)} className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.08em] ${project.visibility === "VISIBLE" ? "bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200" : "bg-slate-100 text-slate-600 ring-1 ring-slate-200"}`}>{project.visibility ?? "HIDDEN"}</button><span className="text-xs text-slate-600">{project.viewCount ?? 0}</span><div className="flex gap-2"><Link aria-label={`Edit ${project.title}`} href={`/admin/projects/${project.id}`} className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:border-[#465fff] hover:text-[#465fff]"><Pencil size={14} /></Link><button aria-label={`Delete ${project.title}`} onClick={() => onRemove(project)} className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:border-red-300 hover:text-red-600"><Trash2 size={14} /></button></div></div>; }
function Empty() { return <div className="grid min-h-[45vh] place-items-center rounded-2xl border border-slate-200 bg-white text-center shadow-sm"><div><p className="font-[family-name:var(--font-punchy)] text-4xl tracking-[-0.06em] text-slate-900">No projects yet</p><Link href="/admin/projects/new" className="mt-5 inline-flex rounded-xl bg-[#465fff] px-4 py-3 text-sm font-medium text-white hover:bg-[#3a4fe6]">Create your first project</Link></div></div>; }
